resources:
- service.yaml
- configmap.yaml
- genesis.yaml
- validator.yaml

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
- name: test-addresses-pstake
  files:
  - configs/keys.json
  - configs/validators.json
  - configs/oracle.json
