---
apiVersion: v1
kind: Service
metadata:
  name: faucet
  labels:
    app.kubernetes.io/name: faucet
spec:
  clusterIP: None
  ports:
    - name: faucet-pstake
      port: 5000
      protocol: TCP
      targetPort: 5000
    - name: faucet-gaia
      port: 5001
      protocol: TCP
      targetPort: 5001
  selector:
    app.kubernetes.io/name: faucet
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: faucet
  namespace: dev-native
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app.kubernetes.io/instance: faucet
      app.kubernetes.io/name: faucet
  template:
    metadata:
      annotations:
        quality: release
        role: api-gateway
        sla: high
        tier: gateway
      labels:
        app.kubernetes.io/instance: faucet
        app.kubernetes.io/type: faucet
        app.kubernetes.io/name: faucet
        app.kubernetes.io/version: '0.1'
    spec:
      imagePullSecrets:
        - name: test-docker-creds
      containers:
        - name: faucet-pstake
          image: persistenceone/faucet-pstake
          imagePullPolicy: Always
          command:
            - bash
            - "-c"
            - |
              npm start
          resources:
            limits:
              cpu: "1"
              memory: 1Gi
            requests:
              cpu: "0.5"
              memory: 0.5Gi
        - name: faucet-gaia
          image: persistenceone/faucet-gaia
          imagePullPolicy: Always
          command:
            - bash
            - "-c"
            - |
              npm start
          resources:
            limits:
              cpu: "1"
              memory: 1Gi
            requests:
              cpu: "0.5"
              memory: 0.5Gi
